server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: ${EUREKA.URI:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: api-auth
          uri: lb://api-auth
          predicates:
            - Path=/auth/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant/**