spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  application:
    name: user-service
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: orders_id

auto:
  create:
    topics:
      enable: true

topic:
  name:
    producer: queueOrdersUsers

server:
  port: 6262

eureka:
  client:
    service-url:
      default-zone: ${EUREKA.URI:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      findOrderCB:
        slidingWindowSize: 8
        minimumNumberOfCalls: 4