spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  application:
    name: user-service

server:
  port: 6262

eureka:
  client:
    service-url:
      default-zone: ${EUREKA.URI:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      createOrderCB:
        slidingWindowSize: 8
        minimumNumberOfCalls: 4
      findOrderCB:
        slidingWindowSize: 8
        minimumNumberOfCalls: 4